stages:
  - test
  - deploy
test:
  stage: test
  image: python:2.7
  script:
    - pip install flake8
    - pip install .
    - flake8 --exclude 'satnogsclient/_version.py' \
             'satnogsclient' \
             'setup.py'
deploy:
  stage: deploy
  image: python:2.7
  before_script:
    - pip install twine
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
    - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
  only:
    refs:
      - tags
    variables:
      - $PYPI_USERNAME
      - $PYPI_PASSWORD
